# Generated by Django 3.2.5 on 2021-10-04 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210916_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default="'0.jpg'", upload_to='user_avatars'),
        ),
    ]
