# Generated by Django 3.2.5 on 2021-11-12 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_user_works'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='biography',
            field=models.TextField(blank=True, null=True, verbose_name='biografia'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Indrizzo di email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='Cognome'),
        ),
    ]
