# Generated by Django 3.2.5 on 2021-11-17 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20211112_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='school',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='appartenuto a'),
        ),
    ]
