# Generated by Django 3.2.5 on 2021-11-21 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_user_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='user_avatars/default_avatar.jpeg', upload_to='user_avatars'),
        ),
        migrations.AlterField(
            model_name='user',
            name='school',
            field=models.CharField(max_length=100, null=True, verbose_name='appartenuto a'),
        ),
        migrations.AlterField(
            model_name='user',
            name='works',
            field=models.ManyToManyField(related_name='users', to='users.Work'),
        ),
    ]
