# Generated by Django 3.2.5 on 2021-11-26 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20211121_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='works',
            field=models.ManyToManyField(blank=True, related_name='users', to='users.Work'),
        ),
    ]
