# Generated by Django 3.2.5 on 2021-11-26 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_user_works'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_type',
            field=models.CharField(blank=True, choices=[('student', 'Studente'), ('public', 'Pubblico')], max_length=50, null=True, verbose_name="tipo d'account"),
        ),
        migrations.AlterField(
            model_name='user',
            name='school',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='appartenuto a'),
        ),
    ]
