# Generated by Django 3.2.5 on 2021-12-20 09:11

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=imagekit.models.fields.ProcessedImageField(default='default_images/default_avatar.jpeg', upload_to='user_avatars'),
        ),
    ]
