# Generated by Django 3.2.5 on 2022-01-02 03:27

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20211227_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='namecard_background',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='user_namecard_background'),
        ),
    ]
