# Generated by Django 3.2.5 on 2022-01-02 04:55

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_user_namecard_background'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='namecard_background',
        ),
        migrations.AddField(
            model_name='user',
            name='sfondo',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='user_backgroundImg'),
        ),
    ]
