# Generated by Django 3.2.5 on 2021-11-20 06:36

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('videoarts', '0002_auto_20211120_1536'),
        ('reviews', '0005_alter_review_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoArtReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=300, verbose_name='titolo')),
                ('content', models.TextField(max_length=1000, verbose_name='testo')),
                ('rate', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videoart_reviews', to=settings.AUTH_USER_MODEL)),
                ('videoart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videoart_reviews', to='videoarts.videoart')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
