# Generated by Django 3.2.5 on 2021-11-21 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_videoartreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoartreview',
            name='content',
            field=models.TextField(verbose_name='testo'),
        ),
    ]
