# Generated by Django 3.2.5 on 2021-11-23 05:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reviews', '0007_alter_videoartreview_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='fav',
            field=models.ManyToManyField(related_name='fav_reviews', to=settings.AUTH_USER_MODEL),
        ),
    ]
