# Generated by Django 3.2.5 on 2021-11-23 06:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reviews', '0008_review_fav'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoartreview',
            name='fav',
            field=models.ManyToManyField(related_name='fav_videoart_reviews', to=settings.AUTH_USER_MODEL),
        ),
    ]
