# Generated by Django 3.2.5 on 2021-11-24 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0009_videoartreview_fav'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='like_it',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
