# Generated by Django 3.2.5 on 2021-11-24 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0012_alter_review_like_it'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoartreview',
            name='like_it',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
