# Generated by Django 3.2.5 on 2021-11-20 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoarts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoart',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='videoart_posters', verbose_name='locandina'),
        ),
        migrations.AlterField(
            model_name='videoart',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='videoart_thumbnails', verbose_name='thumbnail'),
        ),
        migrations.AlterField(
            model_name='videoart',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videoart_files'),
        ),
    ]
