# Generated by Django 3.2.5 on 2021-11-20 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoarts', '0002_auto_20211120_1536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videoart',
            name='art_director',
        ),
        migrations.RemoveField(
            model_name='videoart',
            name='audio_director',
        ),
        migrations.RemoveField(
            model_name='videoart',
            name='casting',
        ),
        migrations.RemoveField(
            model_name='videoart',
            name='costume_designer',
        ),
        migrations.RemoveField(
            model_name='videoart',
            name='director',
        ),
        migrations.RemoveField(
            model_name='videoart',
            name='director_of_photograpy',
        ),
        migrations.RemoveField(
            model_name='videoart',
            name='editor',
        ),
        migrations.RemoveField(
            model_name='videoart',
            name='makeup_artist',
        ),
        migrations.RemoveField(
            model_name='videoart',
            name='music',
        ),
        migrations.RemoveField(
            model_name='videoart',
            name='poster',
        ),
        migrations.RemoveField(
            model_name='videoart',
            name='screenwriter',
        ),
        migrations.RemoveField(
            model_name='videoart',
            name='sound_designer',
        ),
        migrations.RemoveField(
            model_name='videoart',
            name='spacial_effect_supervisor',
        ),
        migrations.AddField(
            model_name='videoart',
            name='artist',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='artista'),
        ),
    ]
