# Generated by Django 3.2.5 on 2021-11-21 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoarts', '0003_auto_20211120_2100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videoart',
            name='duration',
        ),
        migrations.AlterField(
            model_name='videoart',
            name='artist',
            field=models.CharField(max_length=300, null=True, verbose_name='artista'),
        ),
        migrations.AlterField(
            model_name='videoart',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='videoart_thumbnails', verbose_name='thumbnail'),
        ),
        migrations.AlterField(
            model_name='videoart',
            name='video',
            field=models.FileField(null=True, upload_to='videoart_files'),
        ),
    ]
