# Generated by Django 3.2.5 on 2021-11-21 03:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoarts', '0004_auto_20211121_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoart',
            name='year',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2022)], verbose_name='anno'),
        ),
    ]
