# Generated by Django 3.2.5 on 2021-11-23 02:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('videoarts', '0005_alter_videoart_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoart',
            name='fav',
            field=models.ManyToManyField(related_name='fav_videoarts', to=settings.AUTH_USER_MODEL),
        ),
    ]
