# Generated by Django 3.2.5 on 2021-11-24 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoarts', '0006_videoart_fav'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoart',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='movie_posters', verbose_name='locandina'),
        ),
    ]
