# Generated by Django 3.2.5 on 2021-11-25 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoarts', '0010_alter_videoart_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoart',
            name='today',
            field=models.BooleanField(default=False),
        ),
    ]
