# Generated by Django 3.2.5 on 2021-11-25 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoarts', '0011_videoart_today'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoart',
            name='like_it',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
