# Generated by Django 3.2.5 on 2021-12-18 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoarts', '0012_videoart_like_it'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoart',
            name='duration',
            field=models.IntegerField(default=0, verbose_name='durata'),
        ),
    ]
