# Generated by Django 3.2.5 on 2021-12-20 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoarts', '0013_videoart_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoart',
            name='poster',
            field=models.ImageField(blank=True, default='default_images/default_poster.png', null=True, upload_to='videoart_posters', verbose_name='cover image'),
        ),
    ]
