# Generated by Django 3.2.5 on 2021-12-31 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoarts', '0014_alter_videoart_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoart',
            name='animator',
            field=models.CharField(blank=True, max_length=300, verbose_name='animazione'),
        ),
        migrations.AddField(
            model_name='videoart',
            name='art_director',
            field=models.CharField(blank=True, max_length=300, verbose_name='scenografia'),
        ),
        migrations.AddField(
            model_name='videoart',
            name='assistant_director',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='aiuto regia'),
        ),
        migrations.AddField(
            model_name='videoart',
            name='audio_director',
            field=models.CharField(blank=True, max_length=300, verbose_name='audio'),
        ),
        migrations.AddField(
            model_name='videoart',
            name='casting',
            field=models.CharField(blank=True, max_length=300, verbose_name='attori'),
        ),
        migrations.AddField(
            model_name='videoart',
            name='character_designer',
            field=models.CharField(blank=True, max_length=300, verbose_name='character design'),
        ),
        migrations.AddField(
            model_name='videoart',
            name='costume_designer',
            field=models.CharField(blank=True, max_length=300, verbose_name='costume'),
        ),
        migrations.AddField(
            model_name='videoart',
            name='director',
            field=models.CharField(max_length=300, null=True, verbose_name='regia'),
        ),
        migrations.AddField(
            model_name='videoart',
            name='director_of_photograpy',
            field=models.CharField(blank=True, max_length=300, verbose_name='fotografia'),
        ),
        migrations.AddField(
            model_name='videoart',
            name='edition_secretary',
            field=models.CharField(blank=True, max_length=300, verbose_name='segretaria di edizione'),
        ),
        migrations.AddField(
            model_name='videoart',
            name='editor',
            field=models.CharField(blank=True, max_length=300, verbose_name='montaggio'),
        ),
        migrations.AddField(
            model_name='videoart',
            name='makeup_artist',
            field=models.CharField(blank=True, max_length=300, verbose_name='trucco'),
        ),
        migrations.AddField(
            model_name='videoart',
            name='music',
            field=models.CharField(blank=True, max_length=300, verbose_name='musica'),
        ),
        migrations.AddField(
            model_name='videoart',
            name='phonic',
            field=models.CharField(blank=True, max_length=300, verbose_name='fonico di presa diretta'),
        ),
        migrations.AddField(
            model_name='videoart',
            name='screenwriter',
            field=models.CharField(blank=True, max_length=300, verbose_name='sceneggiatura'),
        ),
        migrations.AddField(
            model_name='videoart',
            name='sound_designer',
            field=models.CharField(blank=True, max_length=300, verbose_name='sound'),
        ),
        migrations.AddField(
            model_name='videoart',
            name='spacial_effect_supervisor',
            field=models.CharField(blank=True, max_length=300, verbose_name='effetti speciali'),
        ),
        migrations.AddField(
            model_name='videoart',
            name='team',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='troupe'),
        ),
    ]
