# Generated by Django 3.2.5 on 2021-12-31 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoarts', '0015_auto_20211231_2056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videoart',
            name='director',
        ),
        migrations.AlterField(
            model_name='videoart',
            name='artist',
            field=models.CharField(max_length=300, null=True, verbose_name='regia'),
        ),
    ]
