# Generated by Django 3.2.5 on 2021-12-31 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoarts', '0016_auto_20211231_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoart',
            name='curator',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='curazione'),
        ),
        migrations.AddField(
            model_name='videoart',
            name='performer',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='performer'),
        ),
    ]
