# Generated by Django 3.2.5 on 2021-12-31 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoarts', '0017_auto_20211231_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoart',
            name='performer',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='performance'),
        ),
    ]
