# Generated by Django 3.2.5 on 2021-08-11 05:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('video', models.FileField(upload_to='')),
                ('title', models.CharField(max_length=300, verbose_name='titolo')),
                ('description', models.TextField(max_length=300, verbose_name='descrizione')),
                ('director', models.CharField(max_length=300, verbose_name='regista')),
                ('screenwriter', models.CharField(max_length=300, verbose_name='sceneggiatore')),
                ('casting', models.CharField(max_length=300)),
                ('editor', models.CharField(max_length=300, verbose_name='montatore')),
                ('director_of_photograpy', models.CharField(max_length=300, verbose_name='fotografia')),
                ('audio_director', models.CharField(max_length=300, verbose_name='audio')),
                ('music', models.CharField(max_length=300, verbose_name='musica')),
                ('art_director', models.CharField(max_length=300, verbose_name='scenografia')),
                ('costume_designer', models.CharField(max_length=300, verbose_name='costume')),
                ('makeup_artist', models.CharField(max_length=300, verbose_name='make-up artista')),
                ('spacial_effect_supervisor', models.CharField(max_length=300, verbose_name='effetto speciale')),
                ('sound_designer', models.CharField(max_length=300, verbose_name='sound')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
