# Generated by Django 3.2.5 on 2021-08-11 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='thumnail',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='locandina'),
        ),
    ]
