# Generated by Django 3.2.5 on 2021-08-11 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_thumnail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='create',
            new_name='created',
        ),
        migrations.AlterField(
            model_name='movie',
            name='description',
            field=models.TextField(max_length=1000, verbose_name='descrizione'),
        ),
    ]
