# Generated by Django 3.2.5 on 2021-10-03 08:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movie_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='year',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1900)]),
        ),
    ]
