# Generated by Django 3.2.5 on 2021-11-04 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0011_movie_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='rating',
            field=models.FloatField(default=0),
        ),
    ]
