# Generated by Django 3.2.5 on 2021-11-16 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0014_alter_movie_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
    ]
