# Generated by Django 3.2.5 on 2021-11-19 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0015_alter_movie_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='duration',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
