# Generated by Django 3.2.5 on 2021-11-20 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0017_auto_20211120_1429'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VideoArts',
        ),
    ]
