# Generated by Django 3.2.5 on 2021-11-21 03:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0018_delete_videoarts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='art_director',
            field=models.CharField(blank=True, max_length=300, verbose_name='scenografia'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='audio_director',
            field=models.CharField(blank=True, max_length=300, verbose_name='audio'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='casting',
            field=models.CharField(blank=True, max_length=300, verbose_name='attori'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='costume_designer',
            field=models.CharField(blank=True, max_length=300, verbose_name='costume'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='director_of_photograpy',
            field=models.CharField(blank=True, max_length=300, verbose_name='fotografia'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='editor',
            field=models.CharField(blank=True, max_length=300, verbose_name='montaggio'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='makeup_artist',
            field=models.CharField(blank=True, max_length=300, verbose_name='make-up artist'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='music',
            field=models.CharField(blank=True, max_length=300, verbose_name='musica'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='screenwriter',
            field=models.CharField(blank=True, max_length=300, verbose_name='sceneggiatura'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='sound_designer',
            field=models.CharField(blank=True, max_length=300, verbose_name='sound'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='spacial_effect_supervisor',
            field=models.CharField(blank=True, max_length=300, verbose_name='effetto speciale'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='movie_thumbnails', verbose_name='thumbnail'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='video',
            field=models.FileField(null=True, upload_to='movie_files'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2022)], verbose_name='anno'),
        ),
    ]
