# Generated by Django 3.2.5 on 2021-11-22 07:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0021_movie_fav'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='fav',
        ),
        migrations.AddField(
            model_name='movie',
            name='fav',
            field=models.ManyToManyField(null=True, related_name='fav_movies', to=settings.AUTH_USER_MODEL),
        ),
    ]
