# Generated by Django 3.2.5 on 2021-11-25 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0025_movie_today'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='like_it',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
