# Generated by Django 3.2.5 on 2021-11-26 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0026_movie_like_it'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='makeup_artist',
            field=models.CharField(blank=True, max_length=300, verbose_name='trucco'),
        ),
    ]
