# Generated by Django 3.2.5 on 2021-11-26 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0028_auto_20211126_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='animator',
            field=models.CharField(blank=True, max_length=300, verbose_name='animazione'),
        ),
        migrations.AddField(
            model_name='movie',
            name='character_designer',
            field=models.CharField(blank=True, max_length=300, verbose_name='character design'),
        ),
    ]
