# Generated by Django 3.2.5 on 2021-11-26 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0029_auto_20211126_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='phonic',
            field=models.CharField(blank=True, max_length=300, verbose_name='fonico di presa diretta'),
        ),
    ]
