# Generated by Django 3.2.5 on 2021-11-26 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0030_alter_movie_phonic'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='assistant_director',
            field=models.CharField(max_length=300, null=True, verbose_name='aiuto_regia'),
        ),
    ]
