# Generated by Django 3.2.5 on 2021-11-26 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0031_movie_assistant_director'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='assistant_director',
            field=models.CharField(max_length=300, null=True, verbose_name='aiuto regia'),
        ),
    ]
