# Generated by Django 3.2.5 on 2021-12-19 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0033_alter_movie_assistant_director'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='duration',
            field=models.IntegerField(default=0, verbose_name='durata'),
        ),
    ]
