# Generated by Django 3.2.5 on 2021-12-27 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0035_alter_movie_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='team',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='troupe'),
        ),
    ]
