# Generated by Django 3.2.5 on 2021-12-27 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0036_alter_movie_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='spacial_effect_supervisor',
            field=models.CharField(blank=True, max_length=300, verbose_name='effetti speciali'),
        ),
    ]
